import React, { createContext, useContext, useEffect, useState } from 'react';
import * as SecureStore from 'expo-secure-store';
import { api, ApiConcert, ApiUser, setAccessToken } from '../services/api';
export type Vote = 'yes' | 'no' | 'abstain' | null;
export type TrackStatus = 'Voting' | 'Approved' | 'Rejected' | 'Pending';
export type Track = { id:string; title:string; artist:string; duration:string; key:string; setNumber:number; status:TrackStatus; votes:{yes:number;no:number;abstain:number}; myVote:Vote; comments:{id:string;author:string;text:string}[] };
export type Member = { id:string; name:string; instrument:string; initials:string; role:'Leader'|'Musician' };
export type ChatMessage={id:string;author:'me'|'them';text:string;createdAt:string}; export type Chat={id:string;name:string;role:string;messages:ChatMessage[]}; export type ChatAlert={id:string;chatId:string;text:string;createdAt:string};
type Ctx = { tracks:Track[]; isLeader:boolean; setIsLeader:(v:boolean)=>void; vote:(id:string,v:Exclude<Vote,null>)=>Promise<void>; comment:(id:string,text:string)=>Promise<void>; updateComment:(id:string,text:string)=>Promise<void>; deleteComment:(id:string)=>Promise<void>; setStatus:(id:string,s:TrackStatus)=>Promise<void>; setConcertStatus:(s:'Draft'|'Voting'|'Archived')=>Promise<void>; finalize:()=>Promise<void>; finalized:boolean; votingDeadline:string|null; concert:ApiConcert|null; concertId:number; user:ApiUser|null; isSessionReady:boolean; signIn:(user:ApiUser,token:string)=>Promise<void>; signOut:()=>Promise<void>; members:Member[]; loadMembers:()=>Promise<void>; loadTracks:(concertId:number,playlistId?:number)=>Promise<void>; loadConcertState:(concertId:number)=>Promise<void>; loadComments:(trackId:string)=>Promise<void>; moveTrack:(from:number,to:number)=>Promise<void>; removeTrack:(id:string)=>Promise<void>; chats:Chat[]; chatAlerts:ChatAlert[]; openChatAlert:(id:string)=>void; sendChatMessage:(chatId:string,text:string)=>void };
const seed:Track[] = [
 {id:'1',title:'Midnight City',artist:'M83',duration:'4:03',key:'Am',setNumber:1,status:'Voting',votes:{yes:4,no:0,abstain:1},myVote:null,comments:[{id:'seed-1',author:'Анна',text:'Отлично зайдёт в начале второго блока.'}]},
 {id:'2',title:'Use Somebody',artist:'Kings of Leon',duration:'3:51',key:'C',setNumber:1,status:'Voting',votes:{yes:3,no:1,abstain:1},myVote:'yes',comments:[]},
 {id:'3',title:'Take Me Out',artist:'Franz Ferdinand',duration:'3:57',key:'Em',setNumber:1,status:'Approved',votes:{yes:5,no:0,abstain:0},myVote:'yes',comments:[]},
 {id:'4',title:'Mr. Brightside',artist:'The Killers',duration:'3:43',key:'Db',setNumber:1,status:'Pending',votes:{yes:0,no:0,abstain:0},myVote:null,comments:[]}
];
const initialChats:Chat[]=[
 {id:'anna',name:'Анна Белова',role:'Клавіші',messages:[{id:'a1',author:'them',text:'Я переглянула перший сет. Midnight City залишаємо?',createdAt:'18:42'},{id:'a2',author:'me',text:'Так, він добре відкриває концерт.',createdAt:'18:44'}]},
 {id:'ilya',name:'Ілля Орлов',role:'Гітара',messages:[{id:'i1',author:'them',text:'Для Use Somebody беру Telecaster.',createdAt:'17:18'}]},
 {id:'elena',name:'Олена Романюк',role:'Вокал',messages:[{id:'e1',author:'me',text:'Надішлю фінальну тональність після голосування.',createdAt:'16:30'}]}
];
const Context=createContext<Ctx | null>(null);
export function AppProvider({children}:{children:React.ReactNode}) { const [tracks,setTracks]=useState(seed),[isLeader,setIsLeader]=useState(true),[finalized,setFinalized]=useState(false),[votingDeadline,setVotingDeadline]=useState<string|null>(null),[concert,setConcert]=useState<ApiConcert|null>(null),[concertId,setConcertId]=useState(1),[user,setUser]=useState<ApiUser|null>(null),[isSessionReady,setSessionReady]=useState(false),[members,setMembers]=useState<Member[]>([{id:'1',name:'Володимир Алексеев',instrument:'Руководитель',initials:'В',role:'Leader'},{id:'2',name:'Анна Белова',instrument:'Клавиши',initials:'А',role:'Musician'},{id:'3',name:'Илья Орлов',instrument:'Гитара',initials:'І',role:'Musician'},{id:'4',name:'Сергей Левченко',instrument:'Бас-гитара',initials:'С',role:'Musician'},{id:'5',name:'Денис Марченко',instrument:'Ударные',initials:'Д',role:'Musician'},{id:'6',name:'Елена Романюк',instrument:'Вокалист',initials:'О',role:'Musician'},{id:'7',name:'Алексей Гнатюк',instrument:'Вокалист',initials:'А',role:'Musician'}]),[chats,setChats]=useState(initialChats),[chatAlerts,setChatAlerts]=useState<ChatAlert[]>([]);
 const vote=async(id:string,v:Exclude<Vote,null>)=>{setTracks(x=>x.map(t=>{if(t.id!==id)return t; const n={...t,votes:{...t.votes}}; if(t.myVote)n.votes[t.myVote]--; n.votes[v]++;n.myVote=v;return n})); try { await api.vote(id,v); } catch { /* Локальное состояние остаётся доступным при временном отсутствии сети. */ }};
 const comment=async(id:string,text:string)=>{const saved=await api.comment(id,text);setTracks(x=>x.map(t=>t.id===id?{...t,comments:[...t.comments,{id:String(saved.id),author:saved.author,text:saved.text}]}:t));};
 const updateComment=async(id:string,text:string)=>{await api.updateComment(id,text);setTracks(items=>items.map(track=>({...track,comments:track.comments.map(comment=>comment.id===id?{...comment,text}:comment)})));};
 const deleteComment=async(id:string)=>{await api.deleteComment(id);setTracks(items=>items.map(track=>({...track,comments:track.comments.filter(comment=>comment.id!==id)})));};
 const setStatus=async(id:string,status:TrackStatus)=>{setTracks(x=>x.map(t=>t.id===id?{...t,status}:t));try{await api.setTrackStatus(id,status)}catch{/* Локальный результат остаётся видимым до следующей синхронизации. */}};
 const setConcertStatus=async(status:'Draft'|'Voting'|'Archived')=>{await api.setConcertStatus(concertId,status);setConcert(current=>current?{...current,status}:current);await loadTracks(concertId)};
 useEffect(()=>{(async()=>{try{const token=await SecureStore.getItemAsync('bandset.token');const serializedUser=await SecureStore.getItemAsync('bandset.user');if(token&&serializedUser){const savedUser=JSON.parse(serializedUser) as ApiUser;if(savedUser.name==='Владимир Алексеев'){savedUser.name='Володимир Алексеев';await SecureStore.setItemAsync('bandset.user',JSON.stringify(savedUser));}setAccessToken(token);setUser(savedUser);setIsLeader(savedUser.role==='Leader')}}finally{setSessionReady(true)}})()},[]);
 useEffect(()=>{if(!user)return;let timer:ReturnType<typeof setTimeout>;const incoming=['Підтвердіть, будь ласка, порядок у другому сеті.','Можу підготувати партію до репетиції.','Є ідея для фінальної композиції!'];const schedule=()=>{timer=setTimeout(()=>{const chat=initialChats[Math.floor(Math.random()*initialChats.length)],text=incoming[Math.floor(Math.random()*incoming.length)],time=new Date().toLocaleTimeString('uk',{hour:'2-digit',minute:'2-digit'});setChats(items=>items.map(item=>item.id===chat.id?{...item,messages:[...item.messages,{id:`${Date.now()}`,author:'them',text,createdAt:time}]}:item));setChatAlerts(items=>[{id:`alert-${Date.now()}`,chatId:chat.id,text,createdAt:time},...items]);schedule()},8000+Math.floor(Math.random()*12000))};schedule();return()=>clearTimeout(timer)},[user]);
 const signIn=async(nextUser:ApiUser,token:string)=>{setAccessToken(token);setUser(nextUser);setIsLeader(nextUser.role==='Leader');await SecureStore.setItemAsync('bandset.token',token);await SecureStore.setItemAsync('bandset.user',JSON.stringify(nextUser))}; const signOut=async()=>{setAccessToken(null);setUser(null);await SecureStore.deleteItemAsync('bandset.token');await SecureStore.deleteItemAsync('bandset.user')};
 const loadMembers=async()=>{try{const remote=await api.bandMembers();if(remote.length)setMembers(remote.map(member=>({id:String(member.id),name:member.name,instrument:member.instrument,initials:member.name.slice(0,1).toUpperCase(),role:member.role})))}catch{/* Используем текущий локальный состав, пока API недоступен. */}};
 const loadTracks=async(concertId:number,playlistId?:number)=>{try{const remote=await api.tracks(concertId,playlistId);setTracks(remote.map(t=>({id:String(t.id),title:t.title,artist:t.artist,duration:t.duration,key:t.key,setNumber:t.setNumber,status:t.status,votes:t.votes,myVote:t.myVote,comments:[]})))}catch{/* Локальные данные остаются запасным вариантом, пока API недоступен. */}};
 const loadConcertState=async(nextConcertId:number)=>{setConcertId(nextConcertId);try{const concerts=await api.concerts();const nextConcert=concerts.find(item=>item.id===nextConcertId);if(nextConcert){setConcert(nextConcert);setFinalized(nextConcert.isFinalized);setVotingDeadline(nextConcert.votingDeadline)}}catch{/* Локальное состояние остаётся доступным без сети. */}};
 const loadComments=async(trackId:string)=>{try{const remote=await api.comments(trackId);setTracks(current=>current.map(track=>track.id===trackId?{...track,comments:remote.map(comment=>({id:String(comment.id),author:comment.author,text:comment.text}))}:track))}catch{/* Оставляем доступные локальные комментарии. */}};
 const moveTrack=async(from:number,to:number)=>{if(to<0||to>=tracks.length)return;const next=[...tracks];const [moved]=next.splice(from,1);next.splice(to,0,moved);setTracks(next);try{await api.setTrackOrder(concertId,next.map(t=>Number(t.id)))}catch{/* Порядок останется локально до следующей синхронизации. */}};
 const removeTrack=async(id:string)=>{setTracks(current=>current.filter(track=>track.id!==id));try{await api.deleteTrack(id)}catch{/* После обновления данных сервера трек может появиться снова. */}};
 const finalize=async()=>{await api.finalizeConcert(concertId);setFinalized(true);setConcert(current=>current?{...current,status:'Approved',isFinalized:true}:current)};
 const openChatAlert=(id:string)=>setChatAlerts(items=>items.filter(item=>item.id!==id)); const sendChatMessage=(chatId:string,text:string)=>{const value=text.trim();if(!value)return;setChats(items=>items.map(chat=>chat.id===chatId?{...chat,messages:[...chat.messages,{id:`me-${Date.now()}`,author:'me',text:value,createdAt:new Date().toLocaleTimeString('uk',{hour:'2-digit',minute:'2-digit'})}]}:chat))};
 return <Context.Provider value={{tracks,isLeader,setIsLeader,vote,comment,updateComment,deleteComment,setStatus,setConcertStatus,finalize,finalized,votingDeadline,concert,concertId,user,isSessionReady,signIn,signOut,members,loadMembers,loadTracks,loadConcertState,loadComments,moveTrack,removeTrack,chats,chatAlerts,openChatAlert,sendChatMessage}}>{children}</Context.Provider> }
export const useApp=()=>{const v=useContext(Context);if(!v)throw new Error('Missing AppProvider');return v};
