import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { C, Screen } from '../components/ui';
import { api } from '../services/api';
import { useApp } from '../store/app-store';
import { useLanguage } from '../services/language';

export default function Auth(){
  const router=useRouter(); const {signIn}=useApp(); const {t}=useLanguage(); const [register,setRegister]=useState(false); const [nickname,setNickname]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState<'Leader'|'Musician'>('Musician'); const [instrument,setInstrument]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
  const instruments=[['vocalist','vocalist'],['guitar','guitar'],['bassGuitar','bassGuitar'],['keyboards','keyboards'],['drums','drums']] as const;
  const submit=async()=>{try{setLoading(true);setError('');setMessage('');if(register){if(role==='Musician'&&!instrument){setError(t('selectMemberInstrument'));return;}await api.register(nickname,email,password,role==='Leader'?t('bandLeader'):instrument,role);setMessage(t('accountCreated'));setRegister(false);return;}const data=await api.login(email,password);await signIn(data.user,data.accessToken);router.replace('/')}catch(e){setError(e instanceof Error?e.message:t('actionFailed'))}finally{setLoading(false)}};
  const changeMode=()=>{setRegister(!register);setError('');setMessage('');};
  return <Screen><View style={x.wrap}><View style={x.logo}><Ionicons name="musical-notes" color={C.bg} size={34}/></View><Text style={x.brand}>BandSet</Text><Text style={x.tag}>{register?t('authCreateAccount'):t('authTagline')}</Text>{register?<><TextInput value={nickname} onChangeText={setNickname} style={x.input} placeholder={t('nicknamePlaceholder')} placeholderTextColor={C.muted} autoCapitalize="none"/><Text style={x.roleLabel}>{t('groupStatus')}</Text><View style={x.roles}>{([{value:'Musician',label:t('member')},{value:'Leader',label:t('bandLeader')}] as const).map(item=><Pressable key={item.value} onPress={()=>setRole(item.value)} style={[x.role,role===item.value&&x.roleSelected]}><Text style={[x.roleText,role===item.value&&x.roleTextSelected]}>{item.label}</Text></Pressable>)}</View>{role==='Musician'?<><Text style={x.roleLabel}>{t('instrument')}</Text><View style={x.roles}>{instruments.map(([value,label])=><Pressable key={value} onPress={()=>setInstrument(t(label))} style={[x.role,instrument===t(label)&&x.roleSelected]}><Text style={[x.roleText,instrument===t(label)&&x.roleTextSelected]}>{t(label)}</Text></Pressable>)}</View></>:<Text style={x.leaderHint}>{t('leaderHint')}</Text>}</>:null}<TextInput value={email} onChangeText={setEmail} style={x.input} placeholder="E-mail" placeholderTextColor={C.muted} keyboardType="email-address" autoCapitalize="none"/><TextInput value={password} onChangeText={setPassword} style={x.input} placeholder={t('password')} placeholderTextColor={C.muted} secureTextEntry/>{error?<Text style={x.error}>{error}</Text>:null}{message?<Text style={x.message}>{message}</Text>:null}<Pressable disabled={loading} style={[x.login,loading&&x.disabled]} onPress={submit}>{loading?<ActivityIndicator color={C.bg}/>:<Text style={x.loginText}>{register?t('createAccount'):t('signIn')}</Text>}</Pressable>{!register?<Pressable><Text style={x.forgot}>{t('forgotPassword')}</Text></Pressable>:null}<View style={x.line}/><Pressable style={x.register} onPress={changeMode}><Text style={x.registerText}>{register?t('alreadyHaveAccount'):t('createAccount')}</Text></Pressable></View></Screen>;
}
const x=StyleSheet.create({wrap:{padding:25,flex:1,justifyContent:'center',alignItems:'center',gap:14},logo:{width:76,height:76,borderRadius:22,backgroundColor:C.accent,justifyContent:'center',alignItems:'center'},brand:{color:C.text,fontWeight:'800',fontSize:30,marginTop:8},tag:{color:C.muted,textAlign:'center',marginBottom:12},input:{height:53,alignSelf:'stretch',borderRadius:12,borderWidth:1,borderColor:C.line,color:C.text,paddingHorizontal:15,backgroundColor:C.card},roleLabel:{alignSelf:'stretch',color:C.muted,fontWeight:'800',fontSize:11,letterSpacing:1,marginTop:2},roles:{alignSelf:'stretch',flexDirection:'row',flexWrap:'wrap',gap:8},role:{borderWidth:1,borderColor:C.line,borderRadius:10,paddingHorizontal:11,paddingVertical:8},roleSelected:{borderColor:C.accent,backgroundColor:'#382c12'},roleText:{color:C.muted,fontSize:13,fontWeight:'700'},roleTextSelected:{color:C.accent},leaderHint:{alignSelf:'stretch',color:C.muted,fontSize:12,lineHeight:17},login:{backgroundColor:C.accent,height:52,borderRadius:12,alignSelf:'stretch',alignItems:'center',justifyContent:'center'},disabled:{opacity:.65},loginText:{color:C.bg,fontWeight:'800',fontSize:16},forgot:{color:C.accent,fontWeight:'700',fontSize:13},line:{height:1,backgroundColor:C.line,alignSelf:'stretch',marginVertical:8},register:{borderWidth:1,borderColor:C.line,height:51,borderRadius:12,alignSelf:'stretch',alignItems:'center',justifyContent:'center'},registerText:{color:C.text,fontWeight:'800'},error:{color:C.red,alignSelf:'stretch',fontSize:13},message:{color:C.green,alignSelf:'stretch',fontSize:13}});
