import { useEffect, useState } from 'react';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { api, ApiConcert } from '../services/api';
import { C, IconButton, Pill, Screen, s } from '../components/ui';
import { useApp } from '../store/app-store';
import { useLanguage } from '../services/language';
const fallback:ApiConcert[]=[{id:1,title:'Осенний квартирник',date:'2026-09-12T19:00:00Z',votingDeadline:null,venue:'Art Hall, Киев',description:'',status:'Voting',isFinalized:false},{id:2,title:'Городской фестиваль',date:'2026-10-03T20:30:00Z',votingDeadline:null,venue:'Зелёный театр',description:'',status:'Draft',isFinalized:false}];
export default function Concerts(){const router=useRouter(),{isLeader,user}=useApp(),{t}=useLanguage();const [items,setItems]=useState(fallback),[loading,setLoading]=useState(Boolean(user));useEffect(()=>{if(!user)return;api.concerts().then(setItems).catch(()=>{}).finally(()=>setLoading(false))},[user]);return <Screen><View style={x.header}><IconButton name="arrow-back" onPress={()=>router.back()}/><Text style={x.title}>{t('concerts')}</Text>{isLeader?<IconButton name="add" onPress={()=>router.push('/concert-formats')}/>:<View style={x.empty}/>}</View>{loading?<View style={x.loader}><ActivityIndicator color={C.accent}/></View>:<View style={x.body}>{isLeader?<Pressable onPress={()=>router.push('/concert-formats')} style={x.catalog}><Ionicons name="albums-outline" size={18} color={C.accent}/><View><Text style={x.catalogTitle}>База форматів RadioStars</Text><Text style={x.catalogText}>Створити концерт із готовими варіантами сетів</Text></View><Ionicons name="chevron-forward" size={18} color={C.muted}/></Pressable>:null}<Text style={x.month}>{t('upcomingEvents')}</Text>{items.map(concert=><Concert key={concert.id} concert={concert} onPress={()=>router.push({pathname:'/playlist',params:{concertId:String(concert.id)}})}/>)}</View>}</Screen>}
function Concert({concert,onPress}:{concert:ApiConcert;onPress?:()=>void}){const {locale,t}=useLanguage();const date=new Date(concert.date);const labels:Record<string,string>={Draft:t('draft'),Voting:t('votes'),Approved:t('approved'),Archived:t('archived')};const color=concert.status==='Approved'?C.green:concert.status==='Voting'?C.accent:C.muted;return <Pressable onPress={onPress} style={[s.card,x.item]}><View style={x.date}><Text style={x.day}>{String(date.getDate()).padStart(2,'0')}</Text><Text style={x.dayMonth}>{date.toLocaleString(locale,{month:'short'}).slice(0,3).toUpperCase()}</Text></View><View style={x.content}><Text style={x.name}>{concert.title}</Text><Text style={x.desc}>{date.toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})} · {concert.venue}</Text><View style={x.pill}><Pill text={labels[concert.status]} color={color}/></View></View><Ionicons name="chevron-forward" size={18} color={C.muted}/></Pressable>}
const x=StyleSheet.create({header:{paddingTop:58,paddingHorizontal:18,paddingBottom:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{color:C.text,fontSize:19,fontWeight:'800'},empty:{width:38},loader:{flex:1,alignItems:'center',justifyContent:'center'},body:{padding:20,gap:13},catalog:{padding:14,borderWidth:1,borderColor:'#F6B73C44',backgroundColor:'#F6B73C12',borderRadius:15,flexDirection:'row',alignItems:'center',gap:11},catalogTitle:{color:C.text,fontSize:14,fontWeight:'800'},catalogText:{color:C.muted,fontSize:11,marginTop:3},month:{color:C.muted,fontSize:11,fontWeight:'800',letterSpacing:1,marginTop:6},item:{padding:15,flexDirection:'row',gap:13,alignItems:'center'},date:{backgroundColor:'#283342',borderRadius:12,width:50,height:56,alignItems:'center',justifyContent:'center'},day:{color:C.text,fontSize:23,fontWeight:'800'},dayMonth:{color:C.accent,fontSize:10,fontWeight:'800'},content:{flex:1},name:{color:C.text,fontSize:16,fontWeight:'800'},desc:{color:C.muted,fontSize:12,marginTop:5},pill:{marginTop:10}});
