import { useCallback, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { C, IconButton, Screen, s } from '../components/ui';
import { useApp } from '../store/app-store';
import { api } from '../services/api';
import { useLanguage } from '../services/language';

export default function Profile(){
  const r=useRouter(); const {isLeader,setIsLeader,user,signOut}=useApp(); const {t}=useLanguage(); const [unread,setUnread]=useState(0); const name=user?.name ?? 'Марія Коваленко';
  useFocusEffect(useCallback(()=>{if(!user)return;void api.notifications().then(items=>setUnread(items.filter(item=>!item.isRead).length)).catch(()=>undefined)},[user]));
  const exit=()=>Alert.alert(t('signOutTitle'),t('signOutText'),[{text:t('cancel'),style:'cancel'},{text:t('signOut'),style:'destructive',onPress:()=>void signOut()}]);
  // @ts-ignore Expo Router regenerates this route type when the dev server starts.
  return <Screen><View style={x.head}><IconButton name="arrow-back" onPress={()=>r.back()}/><Text style={x.title}>{t('profile')}</Text><View style={x.blank}/></View><View style={x.body}><View style={x.avatar}><Text style={x.initial}>{name[0]?.toUpperCase()}</Text></View><Text style={x.name}>{name}</Text><Text style={x.email}>{user?.email ?? 'maria@blueecho.band'}</Text><Pressable onPress={()=>r.push('/band')} style={[s.card,x.band]}><Ionicons name="people" size={22} color={C.accent}/><View style={x.flex}><Text style={x.bandName}>Blue Echo</Text><Text style={x.role}>{isLeader?t('bandLeader'):t('musicianRole')}</Text></View><Ionicons name="chevron-forward" size={18} color={C.muted}/></Pressable><Text style={x.label}>{t('demoMode')}</Text><Pressable style={[s.card,x.row]} onPress={()=>setIsLeader(!isLeader)}><Ionicons name="swap-horizontal" size={21} color={C.blue}/><View style={x.flex}><Text style={x.rowTitle}>{t('changeRole')}</Text><Text style={x.rowDesc}>{t('currentRole')}: {isLeader?t('bandLeader'):t('musicianRole')}</Text></View><Ionicons name="chevron-forward" size={18} color={C.muted}/></Pressable><Text style={x.label}>{t('settings')}</Text><Setting icon="cloud-outline" text={t('connectDropbox')} onPress={()=>r.push('/dropbox')}/><Setting icon="notifications-outline" text={t('notifications')} badge={unread} onPress={()=>r.push('/notifications')}/><Setting icon="time-outline" text={t('changeHistory')} onPress={()=>r.push('/history')}/><Setting icon="log-out-outline" text={t('signOut')} danger onPress={exit}/></View></Screen>;
}
function Setting({icon,text,badge,danger,onPress}:{icon:any;text:string;badge?:number;danger?:boolean;onPress?:()=>void}){return <Pressable onPress={onPress} style={[s.card,x.setting]}><Ionicons name={icon} size={20} color={danger?C.red:C.muted}/><Text style={[x.settingText,danger&&x.danger]}>{text}</Text>{badge? <View style={x.badge}><Text style={x.badgeText}>{badge>99?'99+':badge}</Text></View>:null}<Ionicons name="chevron-forward" size={16} color={C.muted}/></Pressable>}
const x=StyleSheet.create({head:{paddingTop:58,paddingHorizontal:18,paddingBottom:22,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:C.text,fontSize:19,fontWeight:'800'},blank:{width:38},body:{padding:20,alignItems:'center',gap:12},avatar:{width:84,height:84,borderRadius:42,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},initial:{color:C.bg,fontSize:35,fontWeight:'800'},name:{color:C.text,fontWeight:'800',fontSize:21},email:{color:C.muted,fontSize:13},band:{alignSelf:'stretch',padding:15,flexDirection:'row',gap:12,alignItems:'center'},flex:{flex:1},bandName:{color:C.text,fontWeight:'800'},role:{color:C.muted,fontSize:12,marginTop:3},label:{color:C.muted,fontWeight:'800',fontSize:11,letterSpacing:1,alignSelf:'stretch',marginTop:16},row:{alignSelf:'stretch',padding:14,flexDirection:'row',alignItems:'center',gap:11},rowTitle:{color:C.text,fontWeight:'800'},rowDesc:{color:C.muted,fontSize:12,marginTop:2},setting:{alignSelf:'stretch',padding:14,flexDirection:'row',alignItems:'center',gap:12},settingText:{color:C.text,fontWeight:'700',flex:1},badge:{minWidth:21,height:21,paddingHorizontal:6,borderRadius:11,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},badgeText:{color:C.bg,fontSize:11,fontWeight:'800'},danger:{color:C.red}});
